# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'IntegrationDemo_SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftui-example-tapresearch
  pod 'TapResearch', '3.0.0-beta1'  

end
