# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftui-example-tapresearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftui-example-tapresearch
  pod 'TapResearch', '~> 3.0.0-beta1'

end
