# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'WallDemo_Swift_UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftui-example-tapresearch
  pod 'TapResearch', '3.7.1--rc0'

end
